### ISSUE TITLE
Pxtone Cross-Platform Libary Create Now?

### ISSUE THREAD

**Issue by KeitoTobi1** [stkchp/pxtnplay#2]
Hi. Keito940. Game Createing Now.
pxtone Collage Use is My Game.
My Game is Cross-Platform.
Libary Create Now?

**Comment by stkchp** [comment]
I will not planning to make library for another language.
If you create game with C++, can use [original C++ source code](http://pxtone.org/developer/) to convert ptcop file to PCM data.
There are many library to play PCM data, for example SDL, rtaudio, portaudio, etc.
`pxtnplay` is a example to processing `ptcop -> PCM -> libao(audio output library)`, I hope this your help.
